"""Create database

Revision ID: ef0d3349b7b7
Revises: 1aa14b4d673b
Create Date: 2024-11-17 02:55:20.278243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0d3349b7b7'
down_revision: Union[str, None] = '1aa14b4d673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'similarity_coef')
    op.add_column('team_member', sa.Column('similarity_coef', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'similarity_coef')
    op.add_column('team', sa.Column('similarity_coef', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
